# Generated by Django 2.2.16 on 2022-05-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220526_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Записи блогов'},
        ),
    ]
