# Generated by Django 2.2.16 on 2022-05-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220527_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',), 'verbose_name_plural': 'Записи блогов'},
        ),
    ]
